
set(CMAKE_INCLUDE_PATH /usr/local/include)
set(CMAKE_LIBRARY_PATH /usr/local/lib)

message("-- CMAKE_INCLUDE_PATH: ${CMAKE_INCLUDE_PATH}")
message("-- CMAKE_LIBRARY_PATH: ${CMAKE_LIBRARY_PATH}")

message("-- CMAKE_SYSTEM_INCLUDE_PATH: ${CMAKE_SYSTEM_INCLUDE_PATH}")
message("-- CMAKE_SYSTEM_LIBRARY_PATH: ${CMAKE_SYSTEM_LIBRARY_PATH}")

include_directories(${CMAKE_INCLUDE_PATH})
link_directories(${CMAKE_LIBRARY_PATH})
